apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exercise-app
spec:
  rules:
  - host: exercise.localtest.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: exercise-app
            port: 
              number: 8080
