apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exercise-db
spec:
  serviceName: exercise-db
  selector:
    matchLabels:
      name: exercise-db
  volumeClaimTemplates:
    - metadata:
        name: db-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Mi
  template:
    metadata:
      labels:
        name: exercise-db
    spec:
      containers:
      - image: mysql:8.0.3
        imagePullPolicy: IfNotPresent
        name:  mysql
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: exercise
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: admin
          - name: MYSQL_ROOT_PASSWORD
            value: root
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-volume