apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ctr-exercise-rest
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ctr-exercise-rest
  template:
    metadata:
      labels:
        name: ctr-exercise-rest
    spec:
      containers:
        - name: exercise-rest
          image: seminar/ctr-exercise-rest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
